language: python

python:
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - pypy
 - pypy3
 - nightly

matrix:
  allow_failures:
    - python: 2.7
      env: BLEEDING=1
    - python: 3.2
      env: BLEEDING=1
    - python: 3.3
      env: BLEEDING=1
    - python: 3.4
      env: BLEEDING=1
    - python: pypy
    - python: pypy3
    - python: nightly

env:
- DJANGO_VERSION=1.7.9
- DJANGO_VERSION=1.8.3
- BLEEDING=1

install:
- if ! [ "$BLEEDING" == "1" ]; then pip install -q -r requirements.txt; fi
- if   [ "$BLEEDING" == "1" ]; then pip install -q -U -r requirements-bleeding.txt; fi
- pip install -q coveralls
- if [ "$DJANGO_VERSION" ]; then pip install -q Django==$DJANGO_VERSION; fi

script: coverage run --source=. manage.py test

after_success:
    coveralls
