language: python

python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5
 - pypy
 - pypy3
 - nightly

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: nightly
    - env: DJANGO_VERSION=LATEST
  exclude:
    # Django 1.9 does not work on python 3.3.
    - python: 3.3
      env: DJANGO_VERSION=1.9.1
    - python: 3.3
      env: DJANGO_VERSION=LATEST
env:
- DJANGO_VERSION=1.8.7
- DJANGO_VERSION=1.9.1
- DJANGO_VERSION=LATEST

install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov flake8
- if [[ $DJANGO_VERSION != "LATEST" ]]; then pip install -q Django==$DJANGO_VERSION; fi
- if [[ $DJANGO_VERSION == "LATEST" ]]; then pip install -U Django; fi

before_script:
  flake8 . | true

script: coverage run --source=. manage.py test

after_success:
- coveralls
- codecov
