language: python

python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - pypy
 - pypy3
 - nightly

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: nightly
    - env: DJANGO_VERSION=LATEST

env:
- DJANGO_VERSION=1.8.18
- DJANGO_VERSION=1.9.9
- DJANGO_VERSION=1.10.7
- DJANGO_VERSION=1.11
- DJANGO_VERSION=LATEST

install:
- pip install -q -r requirements.txt
- pip install -q -r requirements-dev.txt
- if [[ $DJANGO_VERSION != "LATEST" ]]; then pip install -q Django==$DJANGO_VERSION; fi
- if [[ $DJANGO_VERSION == "LATEST" ]]; then pip install -U Django; fi

before_script:
  flake8 .

script: coverage run --source=. manage.py test

after_success:
- coveralls
- codecov
