language: python

python:
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - pypy
 - pypy3
 - nightly

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: nightly

env:
- DJANGO_VERSION=1.7.9
- DJANGO_VERSION=1.8.3

install:
- pip install -q -r requirements.txt
- pip install -q coveralls
- pip install -q Django==$DJANGO_VERSION

script: coverage run --source=. manage.py test

after_success:
    coveralls
