language: python

matrix:
  include:
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: pypy
    - python: pypy3
    - python: nightly
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: nightly

env:
- DJANGO_VERSION=1.7.9
- DJANGO_VERSION=1.8.3
- BLEEDING=1

install:
- pip install -q -r requirements.txt
- pip install -q coveralls
- pip install -q Django==$DJANGO_VERSION
- if [ "$BLEEDING" == "1" ]; then pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U; fi;

script: coverage run --source=. manage.py test

after_success:
    coveralls
