language: python

python:
- 2.7
- 3.3
- 3.4
- pypy
- pypy3

install:
- pip install -q -r requirements.txt
- pip install -q coveralls

script: coverage run --source=. manage.py test

after_success:
    coveralls
